services:
  nginx:
    image: nginx:1.20
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./supporting-data/sites/:/usr/share/nginx/html/
      - ./supporting-data/nginx/conf.d/:/etc/nginx/conf.d/
      - ./supporting-data/nginx/cert/:/etc/nginx/cert/
